apiVersion: k8s.io/v1
kind: Function
metadata:
  name: environ
spec:
  handler: my.environ
  runtime: python2.7
  type: HTTP
  deps: |
    bottle
  function: |
      import time
      from bottle import request, template
      def environ():
        headers = {}
        for x in dict(request.headers):
          headers[x] = dict(request.headers)[x]
        environs = {}
        for x in dict(request.environ):
          environs[x] = str(dict(request.environ)[x])
        return {"method": request.method, "url": request.url, "path": request.path, "headers": headers, "environ": environs}