apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: introspect
  labels:
    app: introspect
    visualize: 'true'
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: introspect
        visualize: 'true'
    spec:
      containers:
      - image: vasu1124/introspect:v1.0
    #    imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
        name: introspect
        env:
        - name: OSENV_EXAMPLE
          value: some_value
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            cpu: 500m
          limits:
            cpu: 1000m
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthzr
            port: 8080
          initialDelaySeconds: 6
          periodSeconds: 5
          timeoutSeconds: 1
          failureThreshold: 2
        ports:
        - name: introspect
          containerPort: 8080
        - name: debug
          containerPort: 3000
        volumeMounts:
        - mountPath: /etc/secret
          name: secret-volume
          readOnly: true
        - mountPath: /etc/config
          name: config-volume
      volumes:
      - name: secret-volume
        secret:
          secretName: mongodb-secret
      - name: config-volume
        configMap:
          name: introspect-config