apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of Resource Config to be Applied
resources:
- config.yaml
- introspect_v1alpha1_uselessmachine.yaml
- introspect-operator-rbac_role.yaml
- introspect-operator-rbac_role_binding.yaml
- deployment.yaml
- service.yaml

# labels added to all Resources
commonLabels:
  app: introspect
