apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: useless.introspect.actvirtual.com
spec:
  group: introspect.actvirtual.com
  version: v1
  scope: Namespaced
  names:
    kind: Useless
    listKind: UselessList
    plural: useless
    singular: useless
  validation:
    # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        spec:
          properties:
            desiredstate:
              type: boolean
