apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: useless.introspect.actvirtual.com
spec:
  group: introspect.actvirtual.com
  names:
    kind: Useless
    listKind: UselessList
    plural: useless
    singular: useless
  scope: Namespaced
  version: v1
