apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: introspect
  namespace: default
spec:
  maxReplicas: 8
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: introspect
  targetCPUUtilizationPercentage: 50
