apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
#  storageClassName: default
